; Taille maximale des fichiers uploadés
upload_max_filesize = 32M
; Taille maximale des requêtes POST
post_max_size = 48M
; Limite de mémoire des scripts PHP (de base 128M)
memory_limit = 512M

; Temps maximum d'exécution d'un script PHP
max_execution_time = 300
; Temps maximum pour l'analyse des données d'entrée
max_input_time = 300

; Fuseau horaire
date.timezone = Europe/Paris

; Cache php
opcache.enable=1